ALTER TABLE `user_account`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `auth_user`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT,
MODIFY COLUMN `user_account_id` int NOT NULL;

ALTER TABLE `post`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT,
MODIFY COLUMN `user_account_id` int NOT NULL,
MODIFY COLUMN `image_id` int NOT NULL;

ALTER TABLE `product`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `annotation`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT,
MODIFY COLUMN `post_id` int NOT NULL,
MODIFY COLUMN `product_id` int NOT NULL;

ALTER TABLE `tag`
MODIFY COLUMN `id` int NOT NULL AUTO_INCREMENT;

ALTER TABLE `post_tag`
MODIFY COLUMN `post_id` int NOT NULL,
MODIFY COLUMN `tag_id` int NOT NULL;
