version: '3'

silent: true

tasks:
  default:
    cmds:
      - "task -a"

  up:
    desc: ローカル開発環境を立ち上げます。
    cmds:
      - "task migrate:local"
      - "docker compose -f ./docker/local/compose.yaml up"

  down:
    desc: ローカル開発環境を削除します。
    cmds:
      - "docker compose -f ./docker/local/compose.yaml down"

  build:
    desc: コンテナイメージのビルドを実行します。
    cmds:
      - "task build:frontend"
      - "task build:backend"

  build:frontend:
    desc: バックエンドコンテナイメージのビルドを実行します。
    cmds:
      - "docker compose -f ./docker/local/compose.yaml build frontend"

  build:backend:
    desc: バックエンドコンテナイメージのビルドを実行します。
    cmds:
      - "docker compose -f ./docker/local/compose.yaml build app"

  migrate:local:
    desc: ローカル環境のDBにマイグレーションを実行します。
    cmds:
      - "docker compose -f ./docker/local/compose.yaml up -d db"
      - "sleep 3"
      - "docker run --rm --network host -v ./db/migrations:/migrations migrate/migrate -path /migrations -database 'mysql://root:root@tcp(127.0.0.1:3306)/hakushi' -verbose up"

  migrate:production:
    desc: ローカル環境のDBにマイグレーションを実行します。
    prompt: "本番環境のDBにマイグレーションを実行します。本当によろしいですか？"
    cmds:
      - sh script/migrate-production.sh
  create-migrate:
    desc: マイグレーションファイルを作成します。
    vars:
      NAME: '{{ default "migrate" .NAME }}'
    prompt: "ファイル名は {{ .NAME }} でよろしいですか？"
    cmds:
      - "docker run -v ./db/migrations:/migrations migrate/migrate create -ext sql -dir /migrations -seq $(date +'%Y%m%d%H%M%S')_{{ .NAME }}"
