// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/yaken-org/hakushi/internal/adapter/handler"
	"github.com/yaken-org/hakushi/internal/adapter/repository"
	"github.com/yaken-org/hakushi/internal/config"
	"github.com/yaken-org/hakushi/internal/infrastructure/database"
	"github.com/yaken-org/hakushi/internal/infrastructure/server"
	"github.com/yaken-org/hakushi/internal/usecase"
)

// Injectors from wire.go:

func InitializeServer(config2 *config.Config, db *sql.DB) (*server.Server, error) {
	postRepository := repository.NewPostRepository(db)
	userAccountRepository := repository.NewUserAccountRepository(db)
	annotationRepository := repository.NewAnnotationRepository(db)
	tagRepository := repository.NewTagRepository(db)
	postTagRepository := repository.NewPostTagRepository(db)
	transactionManager := database.NewTransactionManager(db)
	postUsecase := usecase.NewPostUsecase(postRepository, userAccountRepository, annotationRepository, tagRepository, postTagRepository, transactionManager)
	postHandler := handler.NewPostHandler(postUsecase)
	userAccountUsecase := usecase.NewUserAccountUsecase(userAccountRepository)
	userAccountHandler := handler.NewUserAccountHandler(userAccountUsecase)
	serverServer := server.New(config2, postHandler, userAccountHandler)
	return serverServer, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewPostRepository, repository.NewUserAccountRepository, repository.NewAnnotationRepository, repository.NewTagRepository, repository.NewPostTagRepository)

var usecaseSet = wire.NewSet(usecase.NewPostUsecase, usecase.NewUserAccountUsecase, database.NewTransactionManager)

var handlerSet = wire.NewSet(handler.NewPostHandler, handler.NewUserAccountHandler)
