/* eslint-disable @next/next/no-img-element */
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mySIPMTygSo
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Card, CardHeader, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Link from "next/link"
import React from "react"

export function PostList() {
    return (
        <Card className="w-full max-w-3xl">
            <CardHeader className="pb-0">
                <div className="flex items-center space-x-4">
                    <h1 className="text-3xl font-bold tracking-tighter">Timeline</h1>
                    <Button size="icon" variant="ghost" className="rounded-full w-10 h-10">
                        <CameraIcon className="w-6 h-6" />
                        <span className="sr-only">Camera</span>
                    </Button>
                </div>
            </CardHeader>
            <CardContent className="p-0">
                <div className="space-y-4">
                    <Card className="rounded-xl shadow-none border">
                        <CardHeader className="p-4 flex items-start gap-4">
                            <Avatar className="w-12 h-12 border">
                                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                                <AvatarFallback>AC</AvatarFallback>
                            </Avatar>
                            <div className="flex-1">
                                <div className="flex items-center space-x-2">
                                    <Link href="#" className="font-bold" prefetch={false}>
                                        john
                                    </Link>
                                    <Link href="#" className="text-sm text-secondary" prefetch={false}>
                                        @john • 2m
                                    </Link>
                                </div>
                                <div className="mt-2 leading-tight">This is a really cool post! 🚀✨</div>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0">
                            <img src="/placeholder.svg" width={500} height={250} alt="Image" className="aspect-video object-cover" />
                        </CardContent>
                        <CardFooter className="p-2 grid gap-2 border-t">
                            <div className="flex items-center space-x-2">
                                <Button variant="ghost" size="icon">
                                    <HeartIcon className="w-4 h-4" />
                                    <span className="sr-only">Like</span>
                                    <span className="text-sm sr-only">Like</span>
                                </Button>
                                <Button variant="ghost" size="icon">
                                    <MessageCircleIcon className="w-4 h-4" />
                                    <span className="sr-only">Comment</span>
                                    <span className="text-sm sr-only">Comment</span>
                                </Button>
                                <Button variant="ghost" size="icon">
                                    <SendIcon className="w-4 h-4" />
                                    <span className="sr-only">Share</span>
                                    <span className="text-sm sr-only">Share</span>
                                </Button>
                            </div>
                        </CardFooter>
                    </Card>
                    <Card className="rounded-xl shadow-none border">
                        <CardHeader className="p-4 flex items-start gap-4">
                            <Avatar className="w-12 h-12 border">
                                <AvatarImage src="/placeholder-user.jpg" alt="@shadcn" />
                                <AvatarFallback>AC</AvatarFallback>
                            </Avatar>
                            <div className="flex-1">
                                <div className="flex items-center space-x-2">
                                    <Link href="#" className="font-bold" prefetch={false}>
                                        amelia
                                    </Link>
                                    <Link href="#" className="text-sm text-secondary" prefetch={false}>
                                        @amelia • 5m
                                    </Link>
                                </div>
                                <div className="mt-2 leading-tight">Just had the best coffee at the new cafe downtown! ☕️</div>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0">
                            <img src="/placeholder.svg" width={500} height={250} alt="Image" className="aspect-video object-cover" />
                        </CardContent>
                        <CardFooter className="p-2 grid gap-2 border-t">
                            <div className="flex items-center space-x-2">
                                <Button variant="ghost" size="icon">
                                    <HeartIcon className="w-4 h-4" />
                                    <span className="sr-only">Like</span>
                                    <span className="text-sm sr-only">Like</span>
                                </Button>
                                <Button variant="ghost" size="icon">
                                    <MessageCircleIcon className="w-4 h-4" />
                                    <span className="sr-only">Comment</span>
                                    <span className="text-sm sr-only">Comment</span>
                                </Button>
                                <Button variant="ghost" size="icon">
                                    <SendIcon className="w-4 h-4" />
                                    <span className="sr-only">Share</span>
                                    <span className="text-sm sr-only">Share</span>
                                </Button>
                            </div>
                        </CardFooter>
                    </Card>
                </div>
            </CardContent>
        </Card>
    )
}

function CameraIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M14.5 4h-5L7 7H4a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V9a2 2 0 0 0-2-2h-3l-2.5-3z" />
            <circle cx="12" cy="13" r="3" />
        </svg>
    )
}


function HeartIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
        </svg>
    )
}


function MessageCircleIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z" />
        </svg>
    )
}


function SendIcon(props: React.SVGProps<SVGSVGElement>) {
    return (
        <svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
        >
            <path d="m22 2-7 20-4-9-9-4Z" />
            <path d="M22 2 11 13" />
        </svg>
    )
}
