// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Post struct {
	ID      string `json:"id"`
	ImageID string `json:"imageId"`
	Title   string `json:"title"`
	Content string `json:"Content"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges,omitempty"`
	Nodes    []*Post     `json:"nodes"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string `json:"cursor"`
	Node   *Post  `json:"node,omitempty"`
}

type Query struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DisplayName string `json:"displayName"`
	IconURL     string `json:"iconURL"`
	Email       string `json:"email"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges,omitempty"`
	Nodes    []*User     `json:"nodes"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Cursor string `json:"cursor"`
	Node   *User  `json:"node,omitempty"`
}
