apiVersion: v1
kind: Service
metadata:
  name: hakushi-backend
spec:
  selector:
    app: hakushi-backend
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: hakushi-frontend
spec:
  selector:
    app: hakushi-frontend
  ports:
  - port: 3000
    targetPort: 80
  type: LoadBalancer
