apiVersion: v1
kind: Service
metadata:
  name: hakushi-backend
spec:
  type: LoadBalancer
  selector:
    app: hakushi-backend
  ports:
  - port: 1080
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hakushi-frontend
spec:
  type: LoadBalancer
  selector:
    app: hakushi-frontend
  ports:
  - port: 1180
    targetPort: 80
