name: Build Container Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./docker/production/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/yaken-org/hakushi-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./docker/production/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ghcr.io/yaken-org/hakushi-frontend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
